#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. /data/hare/ci/functions.sh  # die

[[ -s $PASS_FILE ]] || die "Cannot get password from $PASS_FILE"

if ! sudo systemctl start iscsi-initiator-cmu; then
    # XXX-DEBUGME `sudo systemctl start iscsi-initiator-cmu` may fail
    # with the following messages in journalctl output:
    # ```
    # sudo[2678]:  vagrant : TTY=pts/0 ; PWD=/home/vagrant ; USER=root ; COMMAND=/bin/systemctl start iscsi-initiator-cmu
    # sudo[2678]: pam_unix(sudo:session): session opened for user root by vagrant(uid=0)
    # polkitd[763]: Registered Authentication Agent for unix-process:2693:121595 (system bus name :1.41 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
    # systemd[1]: Starting iSCSI initiator for hare64570-test-pcs-cmu.local target...
    # systemd[1]: Starting Open-iSCSI...
    # iscsid[2700]: iSCSI logger with pid=2701 started!
    # systemd[1]: Failed to read PID from file /var/run/iscsid.pid: Invalid argument
    # kernel: Loading iSCSI transport class v2.0-870.
    # systemd[1]: Started Open-iSCSI.
    # kernel: iscsi: registered transport (tcp)
    # iscsi-initiator-cmu[2699]: 192.168.121.26:3260,1 iqn.3000-03.local.hare64570-test-pcs-cmu:fileio
    # iscsi-initiator-cmu[2717]: iscsiadm: No records found
    # systemd[1]: iscsi-initiator-cmu.service: main process exited, code=exited, status=21/n/a
    # systemd[1]: Failed to start iSCSI initiator for hare64570-test-pcs-cmu.local target.
    # systemd[1]: Unit iscsi-initiator-cmu.service entered failed state.
    # systemd[1]: iscsi-initiator-cmu.service failed.
    # sudo[2678]: pam_unix(sudo:session): session closed for user root
    # ```
    # The workaround is to reset-failed and start again.
    sudo systemctl reset-failed iscsi-initiator-cmu
    sudo systemctl start iscsi-initiator-cmu
fi

sudo yum install -y pacemaker pcs

# https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html/Clusters_from_Scratch/_enable_pcs_daemon.html
sudo systemctl start pcsd
sudo systemctl enable pcsd

sudo passwd --stdin hacluster < $PASS_FILE

# `pcs cluster start` will fail if pod-c[12] host names get resolved
# to 127.0.0.1.
sudo sed -i '/^127\.0\.0\.1.*pod-c[12]$/ d' /etc/hosts
