#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. /data/hare/ci/_env  # MERO_COMMIT_REF, RPMSYNC_DIR

sudo mkdir -p /var/mero
for i in {0..9}; do
    sudo dd if=/dev/zero of=/var/mero/disk$i.img bs=1M seek=9999 count=1
    sudo losetup /dev/loop$i /var/mero/disk$i.img
done

if [[ -n ${MERO_COMMIT_REF:-} ]]; then
    # `systemctl start hare-hax` command, called by `bootstrap-node`,
    # will fail unless `mero-kernel` systemd service is installed.
    sudo /data/mero/scripts/install-mero-service

    sudo make -C /data/hare devinstall
else
    repo="ci-storage.mero.colo.seagate.com${RPMSYNC_DIR}"
    if sudo yum-config-manager --add-repo="http://$repo"; then
        # `yum-config-manager` may fail with
        # "Cannot add repo from [...] a duplicate of an existing repo"
        # error message.  This happens when the CI job is retried manually.
        sudo tee -a /etc/yum.repos.d/${repo//\//_}.repo <<< 'gpgcheck=0'
    fi
    sudo yum install -y hare s3server s3cmd
fi

# Current user should be able to write to /var/lib/hare/ directory,
# which is owned by 'hare' group.
sudo usermod --append --groups hare $USER
