#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. /data/hare/ci/_env  # MOTR_COMMIT_REF, RPMSYNC_DIR

if [[ -n ${MOTR_COMMIT_REF:-} ]]; then
    # `systemctl start hare-hax` command, called by `bootstrap-node`,
    # will fail unless `motr-kernel` systemd service is installed.
    sudo /data/motr/scripts/install-motr-service

    # `TERM=dumb` silences `tput: unknown terminal "unknown"` warnings.
    sudo make -C /data/hare TERM=dumb devinstall
else
    repo="cortx-storage.colo.seagate.com${RPMSYNC_DIR}"
    if sudo yum-config-manager --add-repo="http://$repo"; then
        # `yum-config-manager` may fail with
        # "Cannot add repo from [...] a duplicate of an existing repo"
        # error message.  This happens when the CI job is retried manually.
        sudo tee -a /etc/yum.repos.d/${repo//\//_}.repo <<< 'gpgcheck=0'
    fi
    sudo yum install -y cortx-hare cortx-s3server s3cmd
    /data/hare/ci/m0vg/modify-s3server-config
fi

# Current user should be able to write to /var/lib/hare/ directory,
# which is owned by 'hare' group.
sudo usermod --append --groups hare $USER
