#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. /data/hare/ci/_env  # MERO_COMMIT_REF, RPMSYNC_DIR

if [[ -n ${MERO_COMMIT_REF:-} ]]; then
    # `systemctl start hare-hax` command, called by `bootstrap-node`,
    # will fail unless `mero-kernel` systemd service is installed.
    sudo /data/mero/scripts/install-mero-service

    # `TERM=dumb` silences `tput: unknown terminal "unknown"` warnings.
    sudo make -C /data/hare TERM=dumb devinstall
else
    repo="ci-storage.mero.colo.seagate.com${RPMSYNC_DIR}"
    if sudo yum-config-manager --add-repo="http://$repo"; then
        # `yum-config-manager` may fail with
        # "Cannot add repo from [...] a duplicate of an existing repo"
        # error message.  This happens when the CI job is retried manually.
        sudo tee -a /etc/yum.repos.d/${repo//\//_}.repo <<< 'gpgcheck=0'
    fi
    sudo yum install -y eos-hare eos-s3server s3cmd
    /data/hare/ci/m0vg/modify-s3server-config
fi

# Current user should be able to write to /var/lib/hare/ directory,
# which is owned by 'hare' group.
sudo usermod --append --groups hare $USER
