#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
# set -x

# Default s3server configuration is optimized for hardware setups
# and may cause OOM on virtual machines.  This script modifies s3server
# configuration file, reducing memory consumption of s3server.
# Run this script after installing `cortx-s3server` RPM.

sudo sed -E -i.orig \
     -e 's/\<(S3_DAEMON_DO_REDIRECTION): 1.*/\1: 0/' \
     -e 's/\<(S3_ENABLE_STATS): true.*/\1: false/' \
     -e 's/\<(S3_CLOVIS_READ_POOL_MAX_THRESHOLD):.*/\1: 524288000/' \
     -e 's/\<(S3_LIBEVENT_POOL_INITIAL_SIZE):.*/\1: 209715200/' \
     -e 's/\<(S3_LIBEVENT_POOL_MAX_THRESHOLD):.*/\1: 524288000/' \
     -e 's/\<(S3_LIBEVENT_POOL_RESERVE_SIZE):.*/\1: 1048576/' \
     /opt/seagate/cortx/s3/conf/s3config.yaml
