#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
# set -x

if (($# == 0)); then
    cat >&2 <<EOF
Usage: ${0##*/} HOST...

Make sure SSH connection can be established with no
> Are you sure you want to continue connecting (yes/no)?
questions asked.
EOF
    exit 1
fi

kh=~/.ssh/known_hosts
for host in "$@"; do
    ssh-keyscan -t rsa $host
done >>$kh
chmod 0600 $kh
sudo mkdir -p /root/.ssh
sudo cp $kh /root/.ssh/
