#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

test_cluster() {
    local cdf=$1

    time hctl bootstrap --mkfs $cdf
    hctl status
    time hctl shutdown
}

cd /data/hare/

# Server-server Consul agents configuration.
test_cluster ci/m0vg/_test-boot3.yaml

# XXX-TODO: Remove this block after
# http://gitlab.mero.colo.seagate.com/mero/hare/issues/216 is resolved.
. ci/_env
. ci/functions.sh
XXX_with_s3server || exit 0

# 2x2 S3 servers.
cdf=ci/m0vg/_test-boot3-s3.yaml
sed 's/s3: 0/s3: 2/' ci/m0vg/_test-boot3.yaml >$cdf
test_cluster $cdf
