#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. /data/hare/ci/_env  # MOTR_COMMIT_REF
. /data/hare/ci/functions.sh  # _time

# XXX `m0crate-io-conf` executes `consul`, which is /opt/seagate/cortx/hare/bin.
# There should be a better way to add that directory to PATH; see
# https://github.com/Seagate/cortx-hare/pull/382#issuecomment-661012209
export PATH="/opt/seagate/cortx/hare/bin:$PATH"

do_io() {
    utils/m0crate-io-conf >_m0crate-io.yaml
    dd if=/dev/urandom of=/tmp/128M bs=1M count=128
    _time sudo ${MOTR_COMMIT_REF:+/data/motr/clovis/m0crate/}m0crate \
          -S _m0crate-io.yaml
}

test_cluster() {
    local cdf=$1

    time hctl bootstrap --mkfs $cdf
    do_io
    hctl reportbug
    _time hctl shutdown

    time hctl bootstrap --conf-dir /var/lib/hare  # bootstrap on existing conf
    do_io
    hctl reportbug bundle-id /tmp
    _time hctl shutdown
}

cd /data/hare/

sudo mkdir -p /var/motr
for i in {0..9}; do
    sudo dd if=/dev/zero of=/var/motr/disk$i.img bs=1M seek=9999 count=1
    sudo losetup /dev/loop$i /var/motr/disk$i.img
done

for cdf in singlenode.yaml ci-boot1-2ios.yaml; do
    test_cluster cfgen/examples/$cdf
done
