#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

# Don't require passphrase to ssh $OTHER_HOST.
kh=~/.ssh/known_hosts
ssh-keyscan -t rsa $OTHER_HOST >$kh
chmod 0600 $kh
sudo mkdir -p /root/.ssh
sudo cp $kh /root/.ssh

test_cluster() {
    local cdf=$1

    time hctl bootstrap --mkfs $cdf
    hctl status
    time hctl shutdown
}

cd /data/hare/

# Server-server Consul agents configuration.
test_cluster cfgen/examples/ci-boot2.yaml

# Server-client Consul agents configuration.
test_cluster cfgen/examples/ci-boot2-1confd.yaml

# XXX-TODO: Remove this block after
# http://gitlab.mero.colo.seagate.com/mero/hare/issues/216 is resolved.
. ci/_env
. ci/functions.sh
XXX_with_s3server || exit 0

# 2x2 S3 servers.
cdf=cfgen/examples/_ci-boot2_s3.yaml
sed 's/s3: 0/s3: 2/' cfgen/examples/ci-boot2.yaml >$cdf
test_cluster $cdf
