#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. /data/hare/ci/_env  # MERO_COMMIT_REF

# XXX `m0crate-io-conf` executes `consul`, which is /opt/seagate/hare/bin.
# There should be a better way to add that directory to PATH; see
# http://gitlab.mero.colo.seagate.com/mero/hare/merge_requests/248#note_16669
export PATH="/opt/seagate/hare/bin:$PATH"

do_io() {
    utils/m0crate-io-conf >_m0crate-io.yaml
    dd if=/dev/urandom of=/tmp/128M bs=1M count=128
    sudo ${MERO_COMMIT_REF:+/data/mero/clovis/m0crate/}m0crate \
         -S _m0crate-io.yaml
}

test_cluster() {
    local cdf=$1

    time hctl bootstrap --mkfs $cdf
    do_io
    time hctl shutdown

    time hctl bootstrap --conf-dir /var/lib/hare  # bootstrap on existing conf
    do_io
    time hctl shutdown
}

cd /data/hare/
test_cluster cfgen/examples/singlenode.yaml
test_cluster cfgen/examples/ci-boot1-2ios.yaml
