@startuml
skinparam defaultFontName "Ubuntu Mono"

Consul -> Watch: new state of bq/ collection
note right
Either HTTP call
or a script invocation
end note

Watch -> InboxFilter: prepare
note right
sort by epoch (as int),
base64 decode
end note

InboxFilter -> OffsetStorage: get_last_read_epoch()
OffsetStorage -> KV: get 'bq-delivered/{node-name}'
KV --> OffsetStorage
OffsetStorage --> InboxFilter: int value
InboxFilter -> InboxFilter: drop old messages
InboxFilter --> Watch: messages yet to be processed
loop for each message
    Watch -> BQProcessor: proccess(message)
    BQProcessor --> Watch
    Watch -> OffsetStorage: mark_last_read()

    OffsetStorage -> KV: put 'bq-delivered/{node-name}'
    KV --> OffsetStorage
    OffsetStorage --> Watch
end
Watch --> Consul: OK
@enduml
