#!/usr/bin/env bash
set -eu -o pipefail

# Helper script to bootstrap singlenode-setup from scratch.

export SRC_DIR="$(dirname $(readlink -f $0))"

sudo rm -rf /tmp/consul*

touch /tmp/confd

sudo systemctl start consul-agent

cd $SRC_DIR
cfgen/cfgen -D cfgen/dhall/ -o /tmp/ < cfgen/_misc/singlenode.yaml

cat /tmp/consul-kv.json | jq '[.[] | {key, value: (.value | @base64)}]' | consul kv import -
consul reload

sleep 2

sudo systemctl start hax
