#!/usr/bin/env bash
set -eu -o pipefail

#
# This is the Health Check for the Mero confd service.
#
test $(consul kv get processes/0x7200000000000001:0x1 | jq '.state' -r) = "M0_CONF_HA_PROCESS_STARTED"
