#!/usr/bin/env bash
set -eu -o pipefail

#
# Health check for the Mero confd service.
#

FID=$1

case $(systemctl show -p ActiveState m0d@$FID | cut -d= -f2) in
    'active') exit 0;;
    'failed') exit 2;;
    *) exit 1;;
esac
