#!/usr/bin/env bash
set -eu -o pipefail

#
# Health check for the Mero confd service.
#

FID=$1

case $(systemctl is-active m0d@$FID) in
    'active') exit 0;;
    'failed') exit 2;;
    *) exit 1;;
esac
