#!/usr/bin/env bash

#
# Health check for the Mero confd service.
#
CONFD_STATE=$(systemctl status mero-server-confd | sed -e 's/^[ \t]*//' | grep "^Active" | cut -d ' ' -f 2)
# pipefail before the above comman causes it to exit with last unsuccessfull
# command exit code, i.e. 3 (No such process) in case the process is
# inactive.
set -eu -o pipefail

case $CONFD_STATE in
'active')
  exit 0
  ;;
'failed')
  exit 2
  ;;
'inactive')
  exit 1
  ;;
esac
