#!/usr/bin/env bash
set -eu -o pipefail

#
# This is the handler for RC Leader election.
#
# It creates the session with confd health checker and
# tries to acquire the leader lock with this session.
#
# Use it like this:
#
# $ consul watch -type=key -key leader elect-rc-leader
#

get_session_id() {
  consul kv get -detailed leader | awk '/Session/ {print $2}'
}

# If there is no session on the leader key - we should cleanup
# EQ watcher and currently running RC handler before continuing.
# Otherwise just exit - there is nothing to do.
SID=$(get_session_id)
if [ "x$SID" == "x-" ]; then
  pkill -f -9 proto-rc || true
else
  exit 0
fi

die() {
  echo $1
  exit 0
}

SPAYLD='{"Name": "leader", "Checks": ["serfHealth", "service:confd"]}'
SRES=`curl -sX PUT -d "$SPAYLD" http://localhost:8500/v1/session/create`
SID=`echo "$SRES" | jq -r '.ID' 2>/dev/null` || true

test -n "$SID" || die "Session creation failed: $SRES"

# Try to acquire the lock until it's already acquired by someone:
while get_session_id | grep -q ^- || exit 0; do
  consul kv put -acquire -session=$SID leader `hostname` 2>/dev/null && break
  sleep 5
done

# We acquired the lock! Start the EQ watcher.
$HOME/hare/new-rc-leader &
