#!/usr/bin/env bash
set -eu -o pipefail

#
# This is the handler for RC Leader election.
#
# It creates the session with confd health checker and
# tries to acquire the leader lock with this session.
#
# Use it like this:
#
# $ consul watch -type=key -key leader elect-rc-leader
#

get_session_id() {
  consul kv get -detailed leader | awk '/Session/ {print $2}'
}

# If the session is already set - the leader is elected, so
# there is nothing for us to do.
get_session_id | grep -q ^- || exit 0

# Cleanup EQ watcher and currently running RC handler (if any).
pkill -f -9 proto-rc || true

die() {
  echo $1
  exit 0 # Don't stop the watcher.
}

PAYLD='{"Name": "leader", "Checks": ["serfHealth", "service:confd"]}'
RES=`curl -sX PUT -d "$PAYLD" http://localhost:8500/v1/session/create`
SID=`echo "$RES" | jq -r '.ID' 2>/dev/null` || true

test -n "$SID" || die "Session creation failed: $RES"

clean_exit() {
  curl -sX PUT http://localhost:8500/v1/session/destroy/$SID &>/dev/null || true
  exit 0
}

# Try to acquire the lock unless it's already acquired by someone else:
while get_session_id | grep -q ^- || clean_exit; do
  consul kv put -acquire -session=$SID leader `hostname` 2>/dev/null && break
  sleep 5
done

# We've got the lock! Start the EQ watcher.
$HOME/hare/new-rc-leader &
