#!/usr/bin/env bash
set -eu -o pipefail

#
# Get entrypoint data from Consul.
# See rfc/1/README.md for more details.
#
#   $ ./get-entrypoint
#   principal-RM: sage75c1
#   confds:
#     - node: sage75
#       address: 192.168.180.162@tcp:12345:44:101
#     - node: sage75c1
#       address: 192.168.180.166@tcp:12345:44:101

SID=$(consul kv get -detailed leader | awk '/Session/ {print $2}')

echo -n 'principal-RM: '
curl -sX GET http://localhost:8500/v1/session/info/$SID | jq -r '.[] | .Node'

echo 'confds:'
curl -sX GET http://localhost:8500/v1/catalog/service/confd |
    jq -r '.[] | "  - node: \(.Node)
    address: \(.ServiceAddress):\(.ServicePort)"'
