#!/usr/bin/env bash
set -e -o pipefail
# set -x
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '

### Main entry point to all Hare features

# constants
PROG=${0##*/}
SRC_DIR="$(dirname $(readlink -f $0))"
M0_SRC_DIR=${M0_SRC_DIR:-${SRC_DIR%/*}/mero}


die() {
    local LightRed="$(tput bold ; tput setaf 1)"
    local NC="$(tput sgr0)" # No Color
    local error='[ERROR]'

    if [[ -t 2 ]] ; then
        error="$LightRed$error$NC"
    fi

    echo -e "$PROG $error $@" >&2
    exit 1
}

if [[ $SRC_DIR =~ bin/?$ ]]; then
    HARE_BASE_DIR=$SRC_DIR/..
else
    # TODO: '/opt/seagate/hare' prefix can be different, e.g. '/usr'
    HARE_BASE_DIR=/opt/seagate/hare
    [[ -d $HARE_BASE_DIR && -e $HARE_BASE_DIR/bin/hctl ]] ||
        die 'Hare is not installed, please run `make devinstall`.'
fi

usage() {
    cat <<EOF
Usage: $PROG <command> [options]

  Bootstrap, start/stop Mero cluster. Show cluster status.

  Commands:

$(commands_usage)

    help         Show this help screen.
EOF
}

commands_usage() {
    local padding='    '

    for cmd in $(ls -1 $HARE_BASE_DIR/libexec/hare/hare-*); do
        local name=${cmd##*/hare-}
        local info=$(grep -Po '(?<=^###).*' $cmd)
        echo -e "$padding$name\t$info"
    done
}

_help() {
    [[ $1 == stdout ]] && usage || usage >&2
    exit 1
}


# parse CLI options
while true ; do
    case $1 in
        -h|--help|help)  _help stdout ;;

        -*) die "Unknown option '$1', see \`$PROG help\`." ;;
        *)  cmd=${1:-help} ; shift || true ; break ;;
    esac

    shift
done

# process commands
case $cmd in
    help)  _help stdout ;;
    bootstrap|shutdown|status)
        if [[ -d $M0_SRC_DIR/utils ]]; then
            PATH="$M0_SRC_DIR/utils:$PATH"
        fi
        PATH="$HARE_BASE_DIR/libexec/hare:$PATH"
        PATH="$HARE_BASE_DIR/bin:$PATH"
        export PATH

        # TODO: python3.6 version can be different
        PYTHONPATH="$HARE_BASE_DIR/lib/python3.6/site-packages"
        PYTHONPATH="$HARE_BASE_DIR/lib64/python3.6/site-packages:$PYTHONPATH"
        export PYTHONPATH

        exec $HARE_BASE_DIR/libexec/hare/hare-$cmd "$@"
        ;;
    *) die "Unknown command: '$cmd'" ;;
esac
