#!/usr/bin/env bash
set -eu -o pipefail
# set -x
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '

# Install Hare software on the local node.

SRC_DIR="$(dirname $(readlink -f $0))"
M0_SRC_DIR=${M0_SRC_DIR:-${SRC_DIR%/*}/mero}

init_hax() {
    local env_dir=$SRC_DIR/.env

    python3 -m venv $env_dir
    . $env_dir/bin/activate

    pushd $SRC_DIR/hax >/dev/null
    pip3 install wheel flake8 mypy
    python3 setup.py flake8 mypy bdist_wheel
    pip3 install dist/hax-0.0.1-cp36-cp36m-linux_x86_64.whl
    popd >/dev/null
}

create_env_file() {
    export HAX_EXE="$SRC_DIR/.env/bin/hax"
    echo "HAX_EXE=${HAX_EXE}" >$SRC_DIR/systemd/hax-environment
}

install_systemd() {
    sudo mkdir -p /opt/seagate
    sudo mkdir -p /var/mero/hax
    sudo ln -sfn $SRC_DIR /opt/seagate/consul  # XXX s/consul/hare/
    sudo cp $SRC_DIR/systemd/*.service /usr/lib/systemd/system/
}

init_hax
create_env_file
install_systemd

sudo systemctl daemon-reload
