#!/usr/bin/env bash
set -eu -o pipefail

# We are elected!
#
# Notify Mero about the new principal RM (by revoking conf-read-lock) and
# register EQ watcher (for RC handler).
#

# XXX: notify Mero here

get_session_id() {
    consul kv get -detailed leader | awk '/Session/ {print $2}'
}

SID=$(get_session_id)

# Start EQ watcher:
consul watch -type=keyprefix -prefix eq/ $HOME/hare/proto-rc || true

# Cleanup after ourselves:
curl -sX PUT http://localhost:8500/v1/session/destroy/$SID &>/dev/null
