#!/usr/bin/env bash
set -eu -o pipefail

usage() {
    cat <<EOF
Usage: ${0##*/} KEY [INCREMENT]

Safely generates the next integer value of the given KEY
in the Consul KV store using CAS-put operation.

Optional INCREMENT defaults to 1.
EOF
}

if (($# == 0 || $# > 2)); then
    usage >&2
    exit 1
fi

KEY=$1
INCREMENT=${2:-1}

get_current_value() {
    consul kv get $KEY
}

get_new_value() {
    expr $(get_current_value) + $INCREMENT
}

get_current_index() {
    consul kv get -detailed $KEY | awk '/ModifyIndex/ {print $2}'
}

commit_new_value() {
    consul kv put -cas -modify-index=$1 $KEY $2 > /dev/null
}

NEW_VALUE=$(get_new_value)

while ! commit_new_value $(get_current_index) $NEW_VALUE; do
    NEW_VALUE=$(get_new_value)
done

echo $NEW_VALUE
