* Hare - Halon replacement

** The "Fortnight" Prototype (due 2019-Jul-15)

We are able to start and stop m0d services in EOS configuration (aka
"1+0" configuration): 1 data unit, no parity units, 2 hosts or 1 host.
Halon is not used.

Some amount of fault tolerance is required. (If we decided to go quick
and fragile way of not supporting failures in the prototype, we
wouldn't need Consul to achieve this.  But the whole point of this
prototyping exercise is prove that Mero cluster can work without
Halon.)

*** [@vvv] cluster configuration

**** m0cluster.yaml

Host names, IP addresses, disks specification, where to run confd, RM,
IO services.  Something similar to the ~m0genfacts~' "mini config"
file format.

**** collect-facts

- in: m0cluster.yaml
- out: m0cluster-facts/*.json

*collect-facts* script reads m0cluster.yaml, ssh-es to the hosts
mentioned in it, collects configuration data needed for conf.xc
(e.g., ~facter --json processors | jq .processors.count~,
~facter memorysize_mb~) and saves this data in local files.

**** genconf

- in: m0cluster-facts/*.json
- out: conf.xc; Consul KV?

*genconf* builds internal representation of Mero conf graph from
m0cluster-facts data and creates ~conf.xc~ file(s) using Spiel API.

*** ? Hazel, EQ, BQ

- Hazel - the leader (analogous to Halon's Recovery Coordinator)
- EQ - Event Queue
- BQ - Broadcast Queue (of HA notifications)

*** [@mandar] entrypoint requests processor

Static replies will do.  Bonus points for getting this data from
Consul KV.

*** [@dima.c] bootstrapping: Ansible or Salt
**** start/stop m0d services

Prepare configuration files in ~/etc/~, those will be used by systemd.

*** fault tolerance

Handle failures of m0d processes.  Consul watcher to trigger Pacemaker
to do failover?

*** HA notifications

We need those for EES.

*** [@konstantin] fid generation

**** option 1: use the [[https://docs.google.com/document/d/1-td9_sO-bqErDtJYx40J9UEp2zJh4JJUp_yPmm9Knuc/edit][UFID generator]] (the one used by the s3server team)

**** option 2: the RC increments some counter field in the KV

***** Consul has some atomic increments ([[https://en.wikipedia.org/wiki/Compare-and-swap][CAS]])

*** m0d heartbeats

Do we want to utilize ~ha_link~ or come with a simpler mechanism?

*** ? rg2kv

We might want to store subset of Halon's resource graph in Consul KV.
