#!/usr/bin/env bash
set -eu -o pipefail

# Recovery Coordinator (RC) prototype.
#
# Implemented as a Consul watch handler over the Events Queue (EQ)
# in the persistent KV store.
#
# Takes JSON array of events from stdin and processes them one after another.
# Each event is deleted from the queue after processing.
#
# NOTE: depends on jq >= 1.6 - https://stedolan.github.io/jq
#
# Run it like this:
#
#   $ consul watch -type=keyprefix -prefix eq/ proto-rc
#

# Redirect all printouts to the log file with the timestamp prefix:
exec &>> /tmp/consul-$(basename $0).log
exec &> >(stdbuf -oL gawk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0 }')

STOP=0
sig_handler() {
    echo 'RC: signal caught! Exiting...'
    STOP=1
}

sed 's/null//' | jq -r '.[] | "\(.Key) \(.Value | @base64d)"' | {
    trap sig_handler TERM
    while read EPOCH EVENT; do
        echo "RC: $CONSUL_INDEX: Process $EPOCH $EVENT..."
        sleep 10
        consul kv delete $EPOCH
        [[ $STOP -eq 1 ]] && exit 1 || true
    done
}
