#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${FUNCNAME[0]:+${FUNCNAME[0]}:}${LINENO}] '

### ------------------------------------------------------------------
### Start Hare on singlenode setup
### ------------------------------------------------------------------

SRC_DIR="$(dirname $(readlink -f $0))"
M0_SRC_DIR=${M0_SRC_DIR:-${SRC_DIR%/*}/mero}

CONSUL_DATA_DIR=/tmp/consul
CONSUL_LOG=$SRC_DIR/consul.log

init_hax() {
    local env_dir=$SRC_DIR/.env

    python3 -m venv $env_dir
    . $env_dir/bin/activate
    pip3 install -r $SRC_DIR/hax/requirements.txt
}

[[ -d $SRC_DIR/.env ]] || init_hax

echo 'Starting mero' >&2
sudo modprobe lnet
sudo insmod $M0_SRC_DIR/extra-libs/gf-complete/src/linux_kernel/m0gf.ko
sudo insmod $M0_SRC_DIR/m0mero.ko

echo "Starting consul agent (logs will be written to $CONSUL_LOG)" >&2
consul agent -bind='{{GetPrivateIP}}' \
             -server -config-dir=$SRC_DIR \
             -data-dir=$CONSUL_DATA_DIR -bootstrap-expect=1 \
             -client='127.0.0.1 {{GetPrivateIP}}' \
             -ui >$CONSUL_LOG &

while ! consul kv get -keys /; do
    sleep 1
done

echo 'Starting hax' >&2
sudo LD_LIBRARY_PATH=$M0_SRC_DIR/mero/.libs/ $SRC_DIR/env/bin/python \
     $SRC_DIR/hax/hax.py
