#!/usr/bin/env bash
set -eu -o pipefail

SRC_DIR="$(dirname $(readlink -f $0))"
ENV_FILE=$SRC_DIR/systemd/consul-env

usage() {
    echo "Usage: ${0##*/} <client|server> <bind_address> <join_address>"
    echo
    echo "Updates Consul agent startup parameters at $ENV_FILE."
    exit 1
}

(( $# < 3 )) && usage

sudo rm -rf /tmp/consul

mode=$1
bind_addr=$2
join_addr=$3

sed -r -e "s/^(MODE).*/\1=$mode/" \
       -e "s/^(BIND).*/\1=$bind_addr/" \
       -e "s/^(CLIENT).*/\1=127.0.0.1 $bind_addr/" \
       -e "s/^(JOIN).*/\1=${join_addr:+-retry-join $join_addr}/" -i $ENV_FILE
