#!/usr/bin/env bash
set -eu -o pipefail

usage() {
    echo "$0 <service>"
    echo
    echo "Consul watch to monitor the specified service."
    exit 1
}

[[ $# == 1 ]] || usage

SERVICE=$1

export SRC_DIR="$(dirname $(readlink -f $0))"

HANDLER="jq '.[]|\"\(.Service.ID) \([.Checks|.[].Status==\"passing\"]|all)\"'"
exec consul watch -type=service -service=$SERVICE $HANDLER
