#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. ci/_env  # MERO_COMMIT_REF, RPMSYNC_DIR

if [[ -z ${MERO_COMMIT_REF:-} ]]; then
    repo="ci-storage.mero.colo.seagate.com${RPMSYNC_DIR}"
    yum-config-manager --add-repo="http://$repo"
    tee -a /etc/yum.repos.d/${repo//\//_}.repo <<< 'gpgcheck=0'

    yum install -y hare mero-devel
fi

make test
make install
