#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. ci/_env  # MOTR_COMMIT_REF, RPMSYNC_DIR

if [[ -z ${MOTR_COMMIT_REF:-} ]]; then
    repo="cortx-storage.colo.seagate.com${RPMSYNC_DIR}"
    yum-config-manager --add-repo="http://$repo"
    tee -a /etc/yum.repos.d/${repo//\//_}.repo <<< 'gpgcheck=0'

    yum install -y cortx-hare cortx-motr-devel
fi

make check
make test
make install

hctl --help  # this verifies that utils/hare-* have `# :help: ` lines
