@startuml
skinparam defaultFontName "Ubuntu Mono"

(*) -down-> "Get last read epoch" 
--> "Sort messages by epoch"
--> "Drop the ones that have been read"
--> "Process the rest of the messages"
--> "Mark last epoch from the list as 'read'"
--> (*)

@enduml
