#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

set -eu -o pipefail

# TODO: '/opt/seagate/cortx/hare' prefix can be different, e.g. '/usr'
HARE_BASE_DIR=/opt/seagate/cortx/hare

PATH="$HARE_BASE_DIR/libexec:$PATH"
PATH="$HARE_BASE_DIR/bin:$PATH"
export PATH

# TODO: should it be `consul` and PATH=/opt/seagate/cortx/hare/bin:$PATH ?
exec consul agent \
     -node $NODE \
     -node-id $NODE_ID \
     -bind $BIND \
     -client "$CLIENT" \
     $JOIN \
     -config-dir=$CONF/consul-$MODE-conf \
     -log-file=$HOME/seagate/tmp/log.dat \
     -data-dir=$CONF/consul-data-$BIND $EXTRA_OPTS
