#!/usr/bin/env bash
set -eu -o pipefail

# TODO: '/opt/seagate/hare' prefix can be different, e.g. '/usr'
HARE_BASE_DIR=/opt/seagate/hare

PATH="$HARE_BASE_DIR/libexec/hare:$PATH"
PATH="$HARE_BASE_DIR/bin:$PATH"
export PATH

# TODO: should it be `consul` and PATH=/opt/seagate/hare/bin:$PATH ?
exec consul agent -bind $BIND -client "$CLIENT" $JOIN \
     -config-file=/var/lib/hare/consul-$MODE-conf.json \
     -data-dir=/var/lib/hare/consul-$BIND $EXTRA_OPTS
