#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

set -e -o pipefail
# set -x
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '

export

STORAGE='http://cortx-storage.colo.seagate.com'
REPO_PATH=$1

cat <<EOF > /etc/yum.repos.d/motr_last_successful.repo
[motr-dev]
baseurl=$REPO_PATH/last_successful/
gpgcheck=0
name=motr-dev
enabled=1
EOF

cat <<EOF > /etc/yum.repos.d/motr_uploads.repo
[motr-uploads]
baseurl=$REPO_PATH/last_successful_prod/3rd_party/motr/
gpgcheck=0
name=motr-uploads
enabled=1
EOF

# Hashicorp Consul repo
yum -y install yum-utils
yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
