#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

set -eu -o pipefail

# Log changes of status of Consul services (for debugging purposes).
#
# This script is invoked by Consul watch(es) of "service" type
# [https://www.consul.io/docs/agent/watches.html#service].
#
# Example of a log entry:
#
#     2020-05-04 19:28:14 [
#     2020-05-04 19:28:14   {
#     2020-05-04 19:28:14     "Node": "smc23-m10.colo.seagate.com",
#     2020-05-04 19:28:14     "ServiceID": "12",
#     2020-05-04 19:28:14     "ServiceName": "ios",
#     2020-05-04 19:28:14     "status": "online"
#     2020-05-04 19:28:14   },
#     2020-05-04 19:28:14   {
#     2020-05-04 19:28:14     "Node": "smc24-m10.colo.seagate.com",
#     2020-05-04 19:28:14     "ServiceID": "83",
#     2020-05-04 19:28:14     "ServiceName": "ios",
#     2020-05-04 19:28:14     "status": "online"
#     2020-05-04 19:28:14   }
#     2020-05-04 19:28:14 ]
#
# Dump current values to stdout:
#
#   $ consul watch -type=service -service=<ServiceName>
#
# Retrieve the list of services:
#
#   $ consul catalog services

PROG=${0##*/}

usage() {
    cat <<EOF
Usage: . $PROG [<option>]... --log-dir <dir>

Positional arguments:
  --log-dir <dir>  Log directory path
EOF
}

TEMP=$(getopt --options h: \
              --longoptions help,log-dir: \
              --name "$PROG" -- "$@" || true)

eval set -- "$TEMP"

log_dir=$HOME/seagate/var/log/seagate/hare

while true; do
    case "$1" in
        -h|--help)           usage; exit ;;
        --log-dir)           log_dir=$2; shift 2 ;;
        --)                  shift; break ;;
        *)                   break ;;
    esac
done

# Redirect all printouts to the log file with the timestamp prefix:
exec &>> ${log_dir}/${0##*/}.log
exec &> >(stdbuf -oL gawk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0 }')

jq '[.[] | { "Node": .Node.Node,
             "ServiceID": .Service.ID,
             "ServiceName": .Service.Service,
             "status": (if ([.Checks|.[].Status=="passing"]|all)
                          then "online"
                          else "offline"
                        end)
           } ]'
