#!/usr/bin/env bash
set -eu -o pipefail

usage() {
    cat <<EOF
Usage: ${0##*/} <type>

Generate new fid for the specified Motr conf object type.

See the output of \`\$M0_SRC_DIR/utils/m0confgen --types' (2nd column)
for the supported <type> values.
EOF
}

(($# == 1)) || {
    usage >&2
    exit 1
}

TYPE=$1
printf "0x%02x00000000000001:0x%x\n" $TYPE $(next-gen last_fidk 16)
