#!/usr/bin/env bash
#
# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

# NOTE: Thiscript wont work when Hare is installed from RPM.

set -eu -o pipefail

HARE_BASE_DIR=$HOME/seagate/cortx/hare
PYTHONPATH="$HARE_BASE_DIR/lib/python3.6/site-packages"
PYTHONPATH="$HARE_BASE_DIR/lib64/python3.6/site-packages:$PYTHONPATH"
export PYTHONPATH
		
PATH="$HARE_BASE_DIR/bin:$PATH"
export PATH

activate () {
    . .py3venv/bin/activate
}

run_coverage_tool() {
    python ./utils/hare_cov/hare_coverage.py
}

activate
run_coverage_tool
