#!/usr/bin/env bash
set -eu -o pipefail

PROG=${0##*/}

usage() {
    cat <<EOF
Usage: $PROG [OPTION] FID

Get state of the process with given FID from the Consul KV.

Options:
  -h, --help    Show this help and exit.

Examples:

    \$ $PROG 0x7200000000000001:0x2f
    M0_CONF_HA_PROCESS_STARTED

    \$ $PROG not-a-fid-or-unknown-fid
    \$
EOF
}

if (($# != 1)); then
    usage >&2
    exit 1
fi

case $1 in
    -h|--help) usage; exit;;
esac

fid=$1
consul kv export processes/$fid | jq -r '.[].value | @base64d' | jq -r '.state'
