#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

set -eu -o pipefail

PROG=${0##*/}

get_node_name() {
    /opt/seagate/cortx/hare/libexec/node-name
}

usage() {
    cat <<EOF
Usage: $PROG ID

Get service health status from Consul catalogue.

Options:
  -h, --help    Show this help and exit.

Examples:

    \$ $PROG 9
    passed
EOF
}

if (($# != 1)); then
    usage >&2
    exit 1
fi

case $1 in
    -h|--help) usage; exit;;
esac

id=$1
curl -Gs localhost:8500/v1/health/node/$(get_node_name) \
    --data-urlencode "filter=CheckID == \"service:$id\"" |
    jq -r '.[].Status'
