#!/usr/bin/env bash
#
# Copyright (c) 2020-2022 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

# :help: gather Hare forensic data

PROG=${0##*/}
DEFAULT_DEST_DIR=/tmp
DEFAULT_LOG_DIR=/var/lib/hare
DEFAULT_CONF_DIR=/var/log/seagate/hare

usage() {
    cat <<EOF
Usage: $PROG -b <bundleid> -t <path> -c <confstore_url> --systemd_disabled

Create '<dest-dir>/hare/hare_<bundle-id>.tar.gz' archive with Hare
forensic data --- logs and configuration files, which can be used for
reporting and researching Hare bugs.

Positional arguments:
  -b                    Unique bundle-id used to identify support bundles.
  -t                    Location at which support bundle needs to be copied.
  -c                    Configuration directory where Hare
                        config files are present.
  -l                    The directory where the Hare related log files
                        are present.

Options:
  -h, --help   Show this help and exit.
EOF
}

bundle_id=$HOSTNAME
dest_dir=$DEFAULT_DEST_DIR
log_dir=$DEFAULT_LOG_DIR
conf_dir=$DEFAULT_CONF_DIR

TEMP=$(getopt --options hm:b:t:c:l: \
              --longoptions help,systemd-disabled \
              --name "$PROG" -- "$@" || true)

eval set -- "$TEMP"
while true; do
    case "$1" in
        -h|--help)            usage; exit ;;
        -b)                   bundle_id=$2; shift 2 ;;
        -t)                   dest_dir=$2; shift 2 ;;
        -c)                   conf_dir=$2; shift 2 ;;
        -l)                   log_dir=$2; shift 2 ;;
        --)                   shift; break ;;
        *)                    echo 'getopt: internal error...'; exit 1 ;;
    esac
done

echo "Bundle_id: $bundle_id"
echo "dest_dir: $dest_dir"
echo "conf_dir: $conf_dir"
echo "log_dir: $log_dir"

die() {
    echo "$PROG: $*" >&2
    exit 1
}

systemd_journal() {
    local nr_boots_max=10
    local nr_boots=$(sudo journalctl --list-boot | wc -l)
    if ((nr_boots > nr_boots_max)); then
        nr_boots=$nr_boots_max
    fi
    for ((i = 0; i < nr_boots; ++i)); do
        sudo journalctl -b -$i --utc --no-pager > systemd-journal_$i || true
    done
}

running_process_list() {
    ps aux > processes.txt || true
}

case "${1:-}" in
    -h|--help) usage; exit;;
esac

if (($? != 0 && $? != 2)); then
    die "Wrong number of arguments. Type '$PROG --help' for usage."
fi

if [[ -z $bundle_id || -z $dest_dir ]]; then
    die "Invalid argument. Type '$PROG --help' for usage."
fi

if [[ -a $dest_dir && ! -d $dest_dir ]]; then
    die "$dest_dir is not a directory"
fi

# XXX The intermediate `hare` directory is required by the
# CSM Support Bundle spec-ification.
mkdir -p "$dest_dir/hare/$HOSTNAME"
cd "$dest_dir/hare/$HOSTNAME"

exec 5>&2
exec 2> >(tee _reportbug.stderr >&2)

systemd_journal

sudo journalctl --no-pager --full --utc --output=json --unit=pacemaker.service \
     > syslog-pacemaker.json || true

sudo systemctl --all --full --no-pager status {hare,m0,motr,s3}\* \
     > systemctl-status.txt || true

running_process_list

# consul kv output
consul kv get --recurse > consul_kv.log

# cluster status
sudo timeout --kill-after 30 15 hctl status \
     > hctl-status.txt || true

sysconfig_dir='/etc/sysconfig'
[ -d $sysconfig_dir ] || sysconfig_dir='/etc/default'

extra_files=(
    $sysconfig_dir/motr
    /opt/seagate/cortx-prvsnr/pillar/components/cluster.sls
    /opt/seagate/cortx/s3/conf/s3config.yaml
)
for f in ${extra_files[@]}; do
    if [[ -f $f ]]; then
        cp --parents $f . || true
    fi
done

find "$conf_dir" -type f -name 'm0trace.*' | while read trace; do
    ## Disable stderr output to suppress these messages:
    ##
    ## > lt-m0tracedump: Warning: skipping non-existing trace
    ## > descriptor 0x7f977d0bdb00 (orig 0x7ff6ad5c9b00)
    m0tracedump -s -i "$trace" 2>/dev/null | xz > "$trace.yaml.xz" || true
done

cp --parents $conf_dir/* . 2>/dev/null || true
cp -r --parents $conf_dir/consul-{env,server,client}-* . 2>/dev/null || true
cp -r --parents $log_dir/ . 2>/dev/null || true
cp -r --parents /var/log/cluster/ . 2>/dev/null || true

cd ..

# Close copied stderr to avoid usage of $HOSTNAME directory
exec 2>&5

[[ -s $HOSTNAME/_reportbug.stderr ]] || rm $HOSTNAME/_reportbug.stderr

tar --remove-files -czf "hare_${bundle_id}.tar.gz" $HOSTNAME
echo "Created $dest_dir/hare/hare_${bundle_id}.tar.gz"
