#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
# set -x

# :help: gather Hare forensic data

PROG=${0##*/}
DEFAULT_DEST_DIR=/tmp

usage() {
    cat <<EOF
Usage: $PROG [-h | --help] [<bundle-id> <dest-dir>]

Create '<dest-dir>/hare/hare_<bundle-id>.tar.gz' archive with Hare
forensic data --- logs and configuration files, which can be used for
reporting and researching Hare bugs.

Positional arguments:
  bundle-id   Support bundle ID; defaults to the local host name
              (${HOSTNAME%%.*}).
  dest-dir    Target directory; defaults to '$DEFAULT_DEST_DIR'.

Options:
  -h, --help   Show this help and exit.
EOF
}

die() {
    echo "$PROG: $*" >&2
    exit 1
}

case "${1:-}" in
    -h|--help) usage; exit;;
esac

if (($? != 0 && $? != 2)); then
    die "Wrong number of arguments. Type '$PROG --help' for usage."
fi

bundle_id=${1:-${HOSTNAME%%.*}}
dest_dir=${2:-$DEFAULT_DEST_DIR}

if [[ -z $bundle_id || -z $dest_dir ]]; then
    die "Invalid argument. Type '$PROG --help' for usage."
fi

if [[ -a $dest_dir && ! -d $dest_dir ]]; then
    die "$dest_dir is not a directory"
fi

# XXX The intermediate `hare` directory is required by the
# CSM Support Bundle spec-ification.
mkdir -p "$dest_dir/hare/$HOSTNAME"
cd "$dest_dir/hare/$HOSTNAME"

exec 5>&2
exec 2> >(tee _reportbug.stderr >&2)

sudo journalctl --no-pager --full --utc --boot --output short-precise \
     > syslog.txt || true

sudo systemctl --all --full --no-pager status {hare,m0,mero,s3}\* \
     > systemctl-status.txt || true

extra_files=(
    /etc/sysconfig/mero
    /opt/seagate/eos-prvsnr/pillar/components/cluster.sls
    /opt/seagate/s3/conf/s3config.yaml
    $(if [[ -r /etc/corosync/corosync.conf ]]; then
          awk '$1 == "logfile:" { print $2 }' /etc/corosync/corosync.conf
      fi)
)
for f in ${extra_files[@]}; do
    if [[ -f $f ]]; then
        cp --parents $f . || true
    fi
done

cp --parents /var/lib/hare/*.{yaml,json} . 2>/dev/null || true
cp -r --parents /var/log/hare/ . 2>/dev/null || true

cd ..

# Close copied stderr to avoid usage of $HOSTNAME directory
exec 2>&5

[[ -s $HOSTNAME/_reportbug.stderr ]] || rm $HOSTNAME/_reportbug.stderr

tar --remove-files -czf "hare_${bundle_id}.tar.gz" $HOSTNAME
echo "Created $dest_dir/hare/hare_${bundle_id}.tar.gz"
