#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

set -eu -o pipefail
# set -x
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '

# :help: start cluster or local node

PROG=${0##*/}

die() {
    echo "$PROG: $*" >&2
    exit 1
}

usage() {
    cat <<EOF
Usage: $PROG [<option>]...

Starts Hare and Motr services on local or all the nodes in the cluster.

Options:
  --node       Starts hare and motr services on current node only.
  --xprt       Use given motr transport type to generate corresponding motr
               process endpoints. Supported transport types are lnet and libfab.
               Transport type defaults to libfab if not specified.
  -h, --help   Shows this help and exit.
EOF

    exit 1;
}

TEMP=$(getopt --options h \
              --longoptions help,node,xprt: \
              --name "$PROG" -- "$@" || true)

eval set -- "$TEMP"

conf_dir=/var/lib/hare
node=false
xprt='libfab'

while true; do
    case "$1" in
        -h|--help)           usage ;;
        --node)              node=true; shift ;;
        --xprt)              xprt=$2; shift 2 ;;
        --)                  shift; break ;;
        *)                   break ;;
    esac
done

if ! [[ -d $conf_dir ]]; then
    die 'Cluster is not configured on this node.'
fi

if  hctl status > /dev/null 2>&1; then
    die 'Cluster is up and running.'
fi

[[ $xprt == 'lnet' ]] || [[ $xprt == 'libfab' ]] || die "Invalid transport type $xprt"

if $node; then
    start-node
else
    hctl bootstrap -c $conf_dir --xprt $xprt
fi

