#!/usr/bin/env python3
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

# :help: stop the cluster

import getopt
import sys
import logging
import utils
import subprocess
from socket import gethostname
from consul import Consul


def local_node_shutdown():
    cns = Consul()
    node = gethostname()
    processes = utils.processes_node(cns, node)

    for svc in utils.shutdown_sequence:
        if svc in processes:
            utils.stop_parallel([proc for proc in processes[svc]])


def main() -> None:
    try:
        opts, args = getopt.getopt(sys.argv[1:],
                                   "hvc:",
                                   ["help", "verbose", "command", "pcs"])
    except getopt.GetoptError as err:
        sys.exit(err)
    for (opt, value) in opts:
        if (opt == '-v') or (opt == "--verbose"):
            logging.basicConfig(level=logging.DEBUG, format='%(message)s')
        else:
            logging.basicConfig(level=logging.INFO, format='%(message)s')
        if (opt == "--pcs"):
            cmd = '/opt/seagate/cortx/hare/libexec/pcs-node'
            subprocess.call(cmd, shell=True)
        elif (opt == "-c") or (opt == "--command"):
            if value == 'shutdown':
                local_node_shutdown()


if __name__ == '__main__':
    main()
