#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

set -eu -o pipefail
# set -x
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '

PATH=$PATH:/opt/seagate/cortx/hare/bin

PROG=${0##*/}

die() {
    echo "$PROG: $*" >&2
    exit 1
}

usage() {
    cat <<EOF
Usage: $PROG [<option>]...

Options:
  --xprt       Use given motr transport type to generate corresponding motr
               process endpoints. Supported transport types are lnet and libfab.
               Transport type defaults to libfab if not specified.
  -h, --help   Shows this help and exit.
EOF

    exit 1;
}

TEMP=$(getopt --options h \
              --longoptions help,xprt: \
              --name "$PROG" -- "$@" || true)

eval set -- "$TEMP"

xprt='libfab'

while true; do
    case "$1" in
        -h|--help)           usage ;;
        --xprt)              xprt=$2; shift 2 ;;
        --)                  shift; break ;;
        *)                   break ;;
    esac
done

[[ $xprt == 'lnet' ]] || [[ $xprt == 'libfab' ]] || die "Invalid transport type $xprt"

## Fid of the first profile.
##
## Sample output:
## ```
## 0x7000000000000001:0x2e
## ```
first_profile_fid() {
    consul kv get -keys 'm0conf/profiles/' | head -1 | cut -d/ -f3
}

## Return process fid and endpoint of every motr client.
##
## Sample output with transport type as lnet:
## ```
## 0x7200000000000001:0x28 172.28.128.150@tcp:12345:4:1
## 0x7200000000000001:0x2b 172.28.128.150@tcp:12345:4:2
## ```
## Sample output with transport type as libfabric:
## 0x7200000000000001:0x2b inet:tcp:10.230.240.185@5001
## 0x7200000000000001:0x2e inet:tcp:10.230.240.185@5002
## ```
motr_clients() {
    consul kv get -recurse m0conf/nodes |
        # Sample input with transport type as lnet:
        # ```
        # m0conf/nodes/cmu/processes/12/endpoint:172.28.128.150@tcp:12345:2:2
        # m0conf/nodes/cmu/processes/12/services/addb2:37
        # ```
        # Sample input with transport type as libfabric:
        # m0conf/nodes/localhost/processes/29/endpoint:inet:tcp:10.230.250.106@5001
        # m0conf/nodes/localhost/processes/29/services/m0_client_other:31
        # [...]
        # ```
        awk -F/ '/endpoint:/ {ep=$6; sub(/^endpoint:/, "", ep)}
                 /m0_client_other/ {printf("0x7200000000000001:0x%x %s\n", $5, ep)}'
}

hax_endpoint() {
   consul kv get -recurse m0conf/nodes |
   awk -F/ '/endpoint:/ {ep=$6; sub(/^endpoint:/, "", ep)}
            /ha/ {printf("0x7200000000000001:0x%x %s\n", $5, ep)}'
}

## Parameterized version of `motr/m0crate/tests/test1_io.yaml` from
## Motr sources.
m0crate_io_conf() {
    local local_ep=$1
    local hax_ep=$2
    local process_fid=$3

    cat <<EOF
CrateConfig_Sections: [MOTR_CONFIG, WORKLOAD_SPEC]

MOTR_CONFIG:
   MOTR_LOCAL_ADDR: $local_ep
   MOTR_HA_ADDR:    $hax_ep
   PROF: <$(first_profile_fid)>  # Profile fid
   LAYOUT_ID: 9                      # Defines the UNIT_SIZE (9: 1MB)
   IS_OOSTORE: 1                     # Is oostore-mode?
   IS_READ_VERIFY: 0                 # Enable read-verify?
   TM_RECV_QUEUE_MIN_LEN: 16  # Minimum length of the receive queue
   MAX_RPC_MSG_SIZE: 65536    # Maximum rpc message size
   PROCESS_FID: <$process_fid>
   IDX_SERVICE_ID: 1

LOG_LEVEL: 4  # err(0), warn(1), info(2), trace(3), debug(4)

WORKLOAD_SPEC:                # Workload specification section
   WORKLOAD:                  # First Workload
      WORKLOAD_TYPE: 1        # Index(0), IO(1)
      WORKLOAD_SEED: tstamp   # SEED to the random number generator
      OPCODE: 3               # Operation(s) to test: 2-WRITE, 3-WRITE+READ
      IOSIZE: 2m              # Total Size of IO to perform per object
      BLOCK_SIZE: 2m          # In N+K conf set to (N * UNIT_SIZE) for max perf
      BLOCKS_PER_OP: 1        # Number of blocks per motr operation
      MAX_NR_OPS: 1           # Max concurrent operations per thread
      NR_OBJS: 10             # Number of objects to create by each thread
      NR_THREADS: 4           # Number of threads to run in this workload
      RAND_IO: 1              # Random (1) or sequential (0) IO?
      MODE: 1                 # Synchronous=0, Asynchronous=1
      THREAD_OPS: 0           # All threads write to the same object?
      NR_ROUNDS: 1            # Number of times this workload is run
      EXEC_TIME: unlimited    # Execution time (secs or "unlimited")
      SOURCE_FILE: /tmp/128M  # Source data file
EOF
}

hax_tmp(){
    hax_endpoint | while read fid haxep; do
    if [ ! -z "$haxep" -a "$haxep" != " " ]; then
        if [[ $xprt == 'libfab' ]]; then
            ip=$(echo $haxep | awk -F":|@" '{print $3}')
            if ip a | grep -q $ip; then
                echo $haxep
                break
            fi
        else
            ip=${haxep%@*}
            if ip a | grep -q $ip; then  # our IP
                echo $haxep
                break
            fi
        fi
    fi
done
}

motr_clients | while read fid ep; do
    if [ ! -z "$ep" -a "$ep" != " " ]; then
        if [[ $xprt == 'libfab' ]]; then
            ip=$(echo $ep | awk -F":|@" '{print $3}')
            val=$( hax_tmp )
            if ip a | grep -q $ip; then  # our IP
                m0crate_io_conf $ep $val $fid
                break
            fi
        else
            ip=${ep%@*}
            val=$( hax_tmp )
            if ip a | grep -q $ip; then  # our IP
                m0crate_io_conf $ep $val $fid
                break
            fi
        fi
    fi
done
