#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
# set -x

KEY=epoch

usage() {
    cat <<EOF
Usage: ${0##*/}

Increment the '$KEY' integer (monotonically incremented counter)
in the Consul KV store using a Check-And-Set operation.
EOF
}

case "${1:-}" in
    -h|--help) usage; exit;;
esac

if (($# != 0)); then
    usage >&2
    exit 1
fi

current_index() {
    consul kv get -detailed $KEY | awk '/ModifyIndex/ {print $2}'
}

next_epoch() {
    echo $(( $(consul kv get $KEY) + 1 ))
}

commit() {
    local val=$1
    # '-cas' performs a Check-And-Set operation.
    consul kv put -cas -modify-index=$(current_index) $KEY $val > /dev/null
}

n=$(next_epoch)
while ! commit $n; do
    n=$(next_epoch)
done

echo $n
