#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

set -eu -o pipefail
# set -x

PROG=${0##*/}

usage() {
    cat <<EOF
Usage: $PROG [<option>]

Get node name for current node

Options:
  -h, --help            Show this help and exit.
  -c, --conf-dir        config dir where node-name file is present
EOF
}

TEMP=$(getopt --options h: \
              --longoptions help,conf-dir: \
              --name "$PROG" -- "$@" || true)

eval set -- "$TEMP"

conf_dir=$HOME/seagate/var/lib/hare

while true; do
    case "$1" in
        -h|--help)           usage; exit ;;
        -c|--conf-dir)       conf_dir=$2; shift 2 ;;
        --)                  shift; break ;;
        *)                   usage; exit ;;
    esac
done

cat $conf_dir/node-name
