#!/usr/bin/env python3

# Generates a uuid for node using node name as seed.

from socket import getfqdn
import uuid
from sys import argv

name = argv[1] if len(argv) > 1 else getfqdn()
print(uuid.uuid3(uuid.NAMESPACE_DNS, name))
