#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
# set -x

resources=(
    csm-agent
    csm-web
    kibana
    kibana-vip
)
for r in ${resources[@]}; do
    pcs resource delete $r || true
done
