#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
# set -x

hare_dir=/var/lib/hare

count_s3servers() {
    local conf=$1
    if [[ -f $conf ]]; then
        jq -r '.services[] | "\(.name)"' $conf | grep -c '^s3service$'
    else
        echo 0  # XXX-TODO: parse `pcs status` output
    fi
}

for ctrl in c2 c1; do
    conf_dir=consul-server-$ctrl-conf
    for i in $(seq 1 \
                   $(count_s3servers "$hare_dir/$conf_dir/$conf_dir.json")); do
        pcs resource delete s3server-$ctrl-$i || true
    done
done

resources=(
    s3backcons-c{2,1}
    s3backprod
    haproxy-c{2,1}
    statsd
    els-search
    s3auth
    ldap
    rabbitmq
    c{2,1}
    mero-kernel
    lnet
)
for r in ${resources[@]}; do
    pcs resource delete $r || true
done

umount --lazy /var/mero2 || true
umount --lazy /var/mero1 || true
