#!/usr/bin/env bash
set -e -o pipefail

if (($# != 1)); then
    cat >&2 <<EOF
Usage: ${0##*/} CDF

Required argument:
  CDF  Path to the cluster description file.
       Type 'cfgen --help-schema' for format description.
EOF
    exit 1
fi

# Generate configuration files and validate them by bootstrapping the cluster.
hctl bootstrap --mkfs "$1"

hctl shutdown
