#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

set -eu -o pipefail

S3_PREFIX='$HOME/seagate/cortx/s3'
S3_CONFIG=$S3_PREFIX/conf/s3config.yaml
S3_START_SCRIPT=$S3_PREFIX/s3startsystem.sh

die() { echo "$@" >&2; exit 1; }

[[ -e $S3_CONFIG ]] || die "$S3_CONFIG: No such file"
[[ -x $S3_START_SCRIPT ]] || die "$S3_START_SCRIPT: No such executable"

sudo sed -i 's/S3_ENABLE_AUTH_SSL: true/S3_ENABLE_AUTH_SSL: false/g' $S3_CONFIG
sudo sed -i '$ s/$/ --disable_auth=true/' $S3_START_SCRIPT
