#!/usr/bin/env bash
set -eu -o pipefail

# Service status watch handler (just for debug purposes).
#
# Can be run like this:
#
# $ consul watch -type=service -service=confd <$0>
#

# Redirect all printouts to the log file with the timestamp prefix:
exec &>> /var/log/hare/consul-${0##*/}.log
exec &> >(stdbuf -oL gawk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0 }')

jq '[.[] | { "fid": (.Service.ID),
             "status": (if ([.Checks|.[].Status=="passing"]|all)
                          then "online"
                          else "offline"
                        end)
           } ]'
