#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. ci/functions.sh  # ci_job_label, die

ci_docker() {
    (($# > 0)) || die "${FUNCNAME[0]}: Arguments expected"

    [[ $PWD == $WORKSPACE_DIR ]] ||
        die "${FUNCNAME[0]}: Wrong working directory"

    _time docker run --rm --name $(ci_job_label) -v $PWD:/data -w /data/hare \
         $DOCKER_REGISTRY/mero/hare:$CENTOS_RELEASE "$@"

    # Containers run commands as 'root' user.  Restore the ownership.
    sudo chown -R $(id -u):$(id -g) .
}

# Make sure that the build image is up to date.
docker pull $DOCKER_REGISTRY/mero/hare:$CENTOS_RELEASE

if [[ -d $WORKSPACE_DIR ]]; then
    die "${FUNCNAME[0]}: \$WORKSPACE_DIR is not expected to exist"
fi
mkdir -p $WORKSPACE_DIR
cp -a $CI_PROJECT_DIR $WORKSPACE_DIR/

cd $WORKSPACE_DIR

cat >hare/ci/_env <<EOF
MERO_COMMIT_REF=${MERO_COMMIT_REF:-}
RPMSYNC_DIR=${RPMSYNC_DIR:-}

# Disable 'set -x' while assigning secret variables in order for their
# values to not be shown.
_orig_set_flags=\$-
set +x

HARE_CI_S3_ACCESS_KEY=${HARE_CI_S3_ACCESS_KEY:-}
HARE_CI_S3_SECRET_KEY=${HARE_CI_S3_SECRET_KEY:-}

set -\$_orig_set_flags
unset _orig_set_flags
EOF

if [[ -n ${MERO_COMMIT_REF:-} ]]; then
    git clone --recursive http://gitlab.mero.colo.seagate.com/mero/mero.git
    cd mero
    git checkout $MERO_COMMIT_REF
    cd -

    ci_docker ci/docker/build-mero
    #ci_docker ci/docker/build-s3server  # XXX-FIXME issue #216
    ci_docker make build  # build Hare
fi
