#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. ci/common-defs.sh  # ci_docker, die

# Make sure that the build image is up to date.
docker pull $DOCKER_REGISTRY/mero/hare:$CENTOS_RELEASE

if [[ -d $WORKSPACE_DIR ]]; then
    die "${FUNCNAME[0]}: \$WORKSPACE_DIR is not expected to exist"
fi
mkdir -p $WORKSPACE_DIR
cp -a $CI_PROJECT_DIR $WORKSPACE_DIR/

cd $WORKSPACE_DIR

cat > hare/ci/_env <<EOF
MERO_COMMIT_REF=${MERO_COMMIT_REF:-}
RPMSYNC_DIR=${RPMSYNC_DIR:-}
EOF

if [[ -n ${MERO_COMMIT_REF:-} ]]; then
    git clone --recursive http://gitlab.mero.colo.seagate.com/mero/mero.git
    cd mero
    git checkout $MERO_COMMIT_REF
    cd -

    ci_docker ci/docker/build-mero
    ci_docker make build  # build Hare
fi
