#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
# set -x

say() {
    echo "[$(date -u +%T)] $*"
}

outdir=$CI_PROJECT_DIR

# XXX-TODO Collect artifacts from different hosts in parallel.
for vm in $($M0VG status | awk '$2 == "running" {print $1}'); do
    echo "----- $vm -----"

    say 'syslog'
    $M0VG run --vm $vm sudo journalctl --no-pager --full --utc --boot \
        --output short-precise >$outdir/syslog.txt 2>/dev/null

    say 'systemctl status'
    $M0VG run --vm $vm sudo systemctl --all --full --no-pager status \
          {hare,m0,motr,s3}\\* >$outdir/systemctl-status.txt || true

    if [[ -e hare/ci/_$CI_JOB_NAME.errno ]]; then
        say 'Consul logs'
        $M0VG scp $vm:/var/log/hare/consul\*.log $outdir/ &>/dev/null

        say 'm0reportbug'
        $M0VG run --vm $vm \
              sudo ${MERO_COMMIT_REF:+/data/mero/utils/}m0reportbug || true
        $M0VG scp $vm:m0reportbug-\*.tar.xz $outdir/
    fi
    say

    cd $outdir
    for f in {syslog,systemctl,consul,m0reportbug}*; do
        [[ -e $f ]] && mv {,${CI_JOB_NAME}_${vm}_}$f
    done
    cd - >/dev/null
done
