#!/usr/bin/env expect
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#


set usage "Usage: $argv0 <timeout (seconds)> <program> \[<arguments>\]"

proc die {msg {rc 1}} {
    send_error "**ERROR** $msg\n"
    exit $rc
}

switch -- [lindex $argv 0] {
    {-h} -
    {--help} {
        puts $usage
        exit
    }
}
if {[llength $argv] < 2} {
    puts stderr "Invalid command\n$usage"
    exit 1
}

set timeout [lindex $argv 0]

spawn sh -c [lrange $argv 1 end]
expect {
    {: test status: SUCCESS} {}
    eof {}
    timeout {die {Timed out!} 124}
}

set rc [lindex [wait] end]
if {$rc != 0} {die "FAIL $rc" $rc}
