#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. ci/common-defs.sh  # _time, die

[[ -z ${MERO_COMMIT_REF:-} ]] ||
    die "$0 expects \$MERO_COMMIT_REF to be unset or empty"

latest_release_dir=$(readlink -f /releases/eos/BLATEST)

_time yum install -y $latest_release_dir/mero{,-devel}-[0-9]*.rpm
time make rpm  # build Hare rpm

mkdir -vp $RPMSYNC_DIR
cp -v /root/rpmbuild/RPMS/x86_64/* $RPMSYNC_DIR/
cp -v $latest_release_dir/mero{,-devel}-[0-9]*.rpm $RPMSYNC_DIR/
cp -v $latest_release_dir/s3*-[0-9]*.rpm $RPMSYNC_DIR/
cd $RPMSYNC_DIR

# Build local yum repository [https://wiki.centos.org/HowTos/CreateLocalRepos].
createrepo -v .

## The repository should have been created at
## http://ci-storage.mero.colo.seagate.com${RPMSYNC_DIR}
## e.g.
## http://ci-storage.mero.colo.seagate.com/releases/dev/vvv/hare/ci-rpm/B63632/
