#!/usr/bin/env bash
set -eu -o pipefail
export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
set -x

. ci/common-defs.sh  # ci_m0vg_init, ci_success

cd $WORKSPACE_DIR

ci_m0vg_init cmu
_time $M0VG run /data/hare/ci/m0vg/init-node
_time $M0VG run /data/hare/ci/m0vg/test-boot1

ci_success
