apiVersion: v1
kind: PersistentVolume
metadata:
  name: cortx-config-vol-1
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    path: /dev/sdf
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ssc-vm-3947.colo.seagate.com
