apiVersion: v1
kind: Pod
metadata:
  name: cortx-io-pod-1
  labels:
    app: cortx-io-pod-1
spec:
  restartPolicy: Never
  nodeName: ssc-vm-3947.colo.seagate.com
  containers:
  - name: cortx-hare-container
    image: ghcr.io/seagate/cortx-all:2.0.0-86-custom-ci
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 2001
      protocol: TCP
    command: [ "tail", "-f", "/dev/null" ]
    volumeDevices:
      - name: io-sdb-1
        devicePath: /dev/sdb
      - name: io-sdc-1
        devicePath: /dev/sdc
      - name: io-sdd-1
        devicePath: /dev/sdd
      - name: io-sde-1
        devicePath: /dev/sde
    volumeMounts:
    - mountPath: /mnt/etc/cortx
      name: cortx-config-vol-1
  - name: cortx-io-container
    image: ghcr.io/seagate/cortx-all:2.0.0-86-custom-ci
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3002
      protocol: TCP
    command: [ "tail", "-f", "/dev/null" ]
    volumeDevices:
      - name: io-sdb-1
        devicePath: /dev/sdb
      - name: io-sdc-1
        devicePath: /dev/sdc
      - name: io-sdd-1
        devicePath: /dev/sdd
      - name: io-sde-1
        devicePath: /dev/sde
    volumeMounts:
    - mountPath: /mnt/etc/cortx
      name: cortx-config-vol-1
  volumes:
    - name: io-sdb-1
      persistentVolumeClaim:
        claimName: io-sdb-1
    - name: io-sdc-1
      persistentVolumeClaim:
        claimName: io-sdc-1
    - name: io-sdd-1
      persistentVolumeClaim:
        claimName: io-sdd-1
    - name: io-sde-1
      persistentVolumeClaim:
        claimName: io-sde-1
    - name: cortx-config-vol-1
      persistentVolumeClaim:
        claimName: cortx-config-vol-1
  imagePullSecrets:
  - name: cortxregcred
  - name: docregcred
