apiVersion: v1
kind: Service
metadata:
  name: cortx-io-pod-3
spec:
  ports:
  - name: hax
    port: 2001
    protocol: TCP
    targetPort: 2001
  - name: motr1
    port: 3001
    protocol: TCP
    targetPort: 3001
  - name: motr2
    port: 3002
    protocol: TCP
    targetPort: 3002
  - name: motr3
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: cortx-io-pod-3
