apiVersion: v1
kind: Pod
metadata:
  name: cortx-io-pod-3
  labels:
    app: cortx-io-pod-3
spec:
  restartPolicy: Never
  nodeName: ssc-vm-4161.colo.seagate.com
  containers:
  - name: cortx-hare-container
    image: ghcr.io/seagate/cortx-all:2.0.0-86-custom-ci
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 2001
      protocol: TCP
    command: [ "tail", "-f", "/dev/null" ]
    volumeDevices:
      - name: io-sdb-3
        devicePath: /dev/sdb
      - name: io-sdc-3
        devicePath: /dev/sdc
      - name: io-sdd-3
        devicePath: /dev/sdd
      - name: io-sde-3
        devicePath: /dev/sde
    volumeMounts:
    - mountPath: /mnt/etc/cortx
      name: cortx-config-vol-3
  - name: cortx-io-container
    image: ghcr.io/seagate/cortx-all:2.0.0-86-custom-ci
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3002
      protocol: TCP
    command: [ "tail", "-f", "/dev/null" ]
    volumeDevices:
      - name: io-sdb-3
        devicePath: /dev/sdb
      - name: io-sdc-3
        devicePath: /dev/sdc
      - name: io-sdd-3
        devicePath: /dev/sdd
      - name: io-sde-3
        devicePath: /dev/sde
    volumeMounts:
    - mountPath: /mnt/etc/cortx
      name: cortx-config-vol-3
  volumes:
    - name: io-sdb-3
      persistentVolumeClaim:
        claimName: io-sdb-3
    - name: io-sdc-3
      persistentVolumeClaim:
        claimName: io-sdc-3
    - name: io-sdd-3
      persistentVolumeClaim:
        claimName: io-sdd-3
    - name: io-sde-3
      persistentVolumeClaim:
        claimName: io-sde-3
    - name: cortx-config-vol-3
      persistentVolumeClaim:
        claimName: cortx-config-vol-3
  imagePullSecrets:
  - name: cortxregcred
  - name: docregcred
