apiVersion: v1
kind: Service
metadata:
  name: cortx-io-pod-svc-1
  ports:
  - name: hax
    port: 2001
    protocol: TCP
    targetPort: 2001
  - name: confd
    port: 3002
    protocol: TCP
    targetPort: 3002
  publishNotReadyAddresses: true
  selector:
    app: cortx-hare-motr-pod
