kind: PersistentVolume
apiVersion: v1
metadata:
  name: io-sdb-1
spec:
  volumeMode: Block
  capacity:
    storage: 100Gi
  local:
    path: /dev/sdb
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ssc-vm-3947.colo.seagate.com
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: io-sdc-1
spec:
  volumeMode: Block
  capacity:
    storage: 100Gi
  local:
    path: /dev/sdc
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ssc-vm-3947.colo.seagate.com
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: io-sdd-1
spec:
  volumeMode: Block
  capacity:
    storage: 100Gi
  local:
    path: /dev/sdd
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ssc-vm-3947.colo.seagate.com
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: io-sde-1
spec:
  volumeMode: Block
  capacity:
    storage: 100Gi
  local:
    path: /dev/sde
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ssc-vm-3947.colo.seagate.com
