#!/bin/bash
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

# Broadcast IOQ_STOB error to all motr processes.
# Sample payload: {"fid": "0x1:0x4", "conf_sdev": "0x1:0x4", "stob_id": {"domain_fid": "0x1:0x2", "fid": "0x1:0x3"}, "fd": 1, "opcode": 2, "rc": 3, "offset": 4, "size": 1024, "bshift": 1}

h0q bq STOB_IOQ_ERROR "$HARE_RC_EVENT_PAYLOAD"
