on: push
name: Find Secrets
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - name: trufflehog-actions-scan
       uses: edplato/trufflehog-actions-scan@master
